SecurityEssentials/Controllers/LogController.cs
using SecurityEssentials.Core;
using SecurityEssentials.Core.Attributes;
using SecurityEssentials.Core.Identity;
using System;
using System.Linq;
using System.Web.Mvc;

namespace SecurityEssentials.Controllers
{
	[SeAuthorize(Roles = "Admin")]
	public class LogController : SecurityControllerBase
	{
		private readonly ISeContext _context;

		public LogController(ISeContext context, IUserIdentity userIdentity, IAppSensor appSensor) : base(userIdentity, appSensor)
		{
			_context = context ?? throw new ArgumentNullException(nameof(context));
		}

		[HttpGet]
		public ActionResult Index()
		{
			var logs = _context.Log.OrderByDescending(a => a.TimeStamp).Take(10).ToList();
			return View("Index", logs);
		}

	}
}

SecurityEssentials/Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title - Security Essentials Project</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/themes/base/css")
    <meta name="description" content="Security Essentials Project" />
</head>
<body>
    <a href="#mainContent" class="skip-link">Skip to main content</a>
    <nav class="navbar navbar-expand-lg navbar-light bg-light" id="navBarContainer" role="navigation" aria-label="site">
        <a class="navbar-brand" href="#">Security Essentials</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-collapse-1" aria-controls="navbar-collapse-1" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbar-collapse-1">
            <ul class="navbar-nav mr-auto" role="menu">
                <li class="@(ViewBag.Active == "Home" ? "navitem dropdown active" : "dropdown navitem")">
                    <a id="home" class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" aria-haspopup="true" aria-expanded="false">
                        Home @if (ViewBag.Active == "Home")
                        {<text><span class='sr-only'>(current)</span></text>}<span class="caret"></span>
                    </a>
                    <div class="dropdown-menu" role="menu">
                        @Html.ActionLink("Home", "Index", "Home", null, new { @class = "nav-link" })
                        @if (Request.IsAuthenticated)
                        {
                            @Html.ActionLink("Landing", "Landing", "Account", null, new { @class = "nav-link" })
                        }
                        @Html.ActionLink("About", "About", "Home", null, new { Id = "about", @class = "nav-link" })
                        @Html.ActionLink("Contact", "Contact", "Home", null, new { Id = "contact", @class = "nav-link" })
                    </div>
                </li>
                @if (Request.IsAuthenticated)
                {
                    <li class="@(ViewBag.Active == "Admin" ? "navitem dropdown active" : "navitem dropdown")">
                        <a id="admin" class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" aria-haspopup="true" aria-expanded="false">
                            Admin @if (ViewBag.Active == "Admin")
                            {<text><span class='sr-only'>(current)</span></text>}<span class="caret"></span>
                        </a>
                        <div class="dropdown-menu" role="menu" aria-labelledby="admin">
                            @if (User.IsInRole("Admin"))
                            {
                                @Html.ActionLink("System Log", "Index", "Log", null, new { Id = "log", @class = "nav-link" })
                                @Html.ActionLink("Manage Users", "Index", "User", null, new { Id = "manageUsers", @class = "nav-link" })
                                <div class="dropdown-divider"></div>
                            }
                            @Html.ActionLink("Manage My Account", "Edit", "User", new { Id = User.Identity.GetUserId() }, new { Id = "manageAccount", @class = "nav-link" })
                            @Html.ActionLink("Change Password", "ChangePassword", "Account", routeValues: null, htmlAttributes: new { title = "Manage", id = "changePassword", @class = "nav-link" })
                            @Html.ActionLink("Change Email", "ChangeEmailAddress", "Account", routeValues: null, htmlAttributes: new { title = "Manage", id = "changeEmailAddress", @class = "nav-link" })
                            @Html.ActionLink("Change Security Information", "ChangeSecurityInformation", "Account", null, new { Id = "changeSecurityInformation", @class = "nav-link" })
                            @Html.ActionLink("View Account Log", "Log", "User", new { Id = User.Identity.GetUserId() }, new { Id = "accountLog", @class = "nav-link" })
                        </div>
                    </li>
                }
            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </nav>

    <main id="mainContent" class="container body-content" role="main">
        @RenderBody()
    </main>
    <hr />
    <footer role="contentinfo">
        <nav class="navbar navbar-light bg-faded" id="bottomNav" role="navigation" aria-label="site">
            <p>&copy; @DateTime.Now.Year - Security Essentials Project</p>
        </nav>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @*@Scripts.Render("~/bundles/jqueryui")*@
    @Scripts.Render("~/bundles/antiforgerytoken")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

SecurityEssentials/Views/Shared/_Recaptcha.cshtml
@using Recaptcha.Web.Mvc
@Html.Recaptcha()